admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

animal:
    resource: "@AnimalBundle/Resources/config/routing.yml"
    prefix:   /

base:
    resource: "@BaseBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

