front_homepage:
    pattern:  /
    defaults: { _controller: FrontBundle:Default:index }

front_search:
    pattern: /search
    defaults: { _controller: FrontBundle:Search:search }
    requirements:
        _method: post

front_animal_homepage:
    pattern: /animals
    defaults: { _controller: FrontBundle:Animal:index }
front_animal_show:
    pattern: /animals/{id}/show
    defaults: { _controller: FrontBundle:Animal:show }
    requirements:
        id: \d+

front_species_show:
    pattern: /species/{id}/show
    defaults: { _controller: FrontBundle:Species:show }
    requirements:
        id: \d+