front_homepage:
    pattern:  /
    defaults: { _controller: FrontBundle:Default:index }

front_search:
    pattern: /search
    defaults: { _controller: FrontBundle:Search:search }
    requirements:
        _method: post

front_animal_homepage:
    pattern: /animals
    defaults: { _controller: FrontBundle:Animal:index }
front_animal_show:
    pattern: /animals/{id}/show
    defaults: { _controller: FrontBundle:Animal:show }
    requirements:
        id: \d+

front_species_show:
    pattern: /species/{id}/show
    defaults: { _controller: FrontBundle:Species:show }
    requirements:
        id: \d+

front_event_add:
    pattern: /event/{id}/add
    defaults: { _controller: FrontBundle:Event:add }
    requirements:
        id: \d+
front_event_new:
    pattern: /event/new
    defaults: { _controller: FrontBundle:Event:new }
front_event_create_new:
    pattern: /event/create/new
    defaults: { _controller: FrontBundle:Event:createnew }
    requirements:
        _method: post
front_event_create_add:
    pattern: /event/create/add
    defaults: { _controller: FrontBundle:Event:createadd }
    requirements:
        _method: post