<?php

namespace Site\AnimalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimalRepository extends EntityRepository
{
	public function findAllBySpecies()
	{
		$query = $this->_em->createQuery('SELECT a FROM Site\AnimalBundle\Entity\Animal a LEFT JOIN a.species s ORDER BY s.commonName,a.name ASC');
		return $query->getResult();
	}
}
