<?php

namespace Site\AnimalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
	public function findAllByAnimalId($id)
	{

	}

	public function paginateByDate($page, $limit)
	{

		$offset = $limit * ($page - 1);
		$qb = $this->createQueryBuilder('e')
					->orderBy('e.date', 'DESC')
					->setFirstResult($offset)
					->setMaxResults($limit);
		$query = $qb->getQuery();
		return $query->getResult();					
	}
}
