<?php

namespace Site\AnimalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpeciesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeciesRepository extends EntityRepository
{
	public function findAllOrderByName()
	{
		$qb = $this->createQueryBuilder('s')->orderBy('s.commonName', 'ASC');
		$query = $qb->getQuery();
		return $query->getResult();
	}

	public function getExistingAnimalsBySpecies()
	{
		$result = [];
		$total = 0;
		$totalSpecies = 0;
		$sp = $this->findAll();
		foreach ($sp as $species) {
			$r = 0;
			$totalSpecies += 1;
			$animals = $species->getAnimals();
			if(count($animals)>0){
				foreach ($animals as $animal) {
					if($animal->getStatus() == "présent"){
						$r += 1;
					}
				}
			}
			$total += $r;
			$result[$species->getCommonName()] = $r;
		}
		$result["totalSpecies"] = $totalSpecies;
		$result["total"] = $total;
		return $result;
	}
}
