<?php

namespace Site\AnimalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpeciesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeciesRepository extends EntityRepository
{
	public function findAllOrderByName()
	{
		$qb = $this->createQueryBuilder('s')->orderBy('s.commonName', 'ASC');
		$query = $qb->getQuery();
		return $query->getResult();
	}
}
