parameters:
#    base.example.class: Site\BaseBundle\Example

services:
    site.basebundle.services.paginator:
        class: Site\BaseBundle\Services\Paginator
        arguments:
            - "@doctrine.orm.entity_manager"
