<?php

namespace Site\ZooBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ZooRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZooRepository extends EntityRepository
{
}
